### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by xxxtonixxx** [Caballerog/ng2-inline-editor#59]
- [ ] Change name to `ngx-inline-editor` or `ng-inline-editor` and move it to @qontu org
- [ ] To do test to the project
- [ ] Rewrite README.md
- [ ] Create new examples using the new features and possibilities
- [ ] Create documentation into the source code (using [compodoc](https://github.com/compodoc/compodoc))
- [ ] Use [semver](http://semver.org/)

**Comment by Caballerog** [comment]
I Just update the roadmap, including several features basic to do in 1.0

**Comment by KeithGillette** [comment]
Hi @xxxtonixxx & @Caballerog — I've seen a few new commits in the past couple of months. Would either of you be willing to provide a status update on the project? I know you've both been busy, so not expecting v1.0.0 anytime soon, but curious to know if there's likelihood of fixes for the build (#125) & AOT (#127) anytime soon. Thanks for this library!
